services:
  demo:
  wmts:
    md:
      # metadata used in capabilities documents
      title: City Data Amsterdam
      abstract: Map tile service Gemeente Amsterdam
      online_resource: https://data.amsterdam.nl/
      contact:
        organization: Gemeente Amsterdam
        city: Amsterdam
        country: Netherlands
        email: datapunt@amsterdam.nl
    restful: false
    kvp: true

caches:
  cache_28992:
    grids: [grid_28992]
    sources: [publieke_werken_2500_1943_28992]
    cache_dir: /mnt/tiles
    format: image/png
    cache:
      type: file
      directory_layout: tms

  cache_4326:
    grids: [grid_4326]
    sources: [publieke_werken_2500_1943_3857]
    cache_dir: /mnt/tiles
    format: image/png
    cache:
      type: file
      directory_layout: tms

sources:
  publieke_werken_2500_1943_28992:
    type: wms
    req:
      url: http://mapserver/maps/publieke-werken
      layers: publieke-werken-2500-1943-28992
      transparent: true

  publieke_werken_2500_1943_3857:
    type: wms
    req:
      url: http://mapserver/maps/publieke-werken
      layers: publieke-werken-2500-1943-3857
      transparent: true

grids:
  grid_28992:
    srs: EPSG:28992
    tile_size: [256, 256]
    origin: sw
    res: [3440.64,1720.32,860.16,430.08,215.04,107.52,53.76,26.88,13.44,6.72,3.36,1.68,0.84,0.42,0.21,0.105,0.0525]
    #     0       1       2      3      4      5      6     7     8     9    10   11   12   13   14   15    16
    bbox: [-285401.920,22598.080,595401.9199999999,903401.9199999999]

  grid_4326:
    base: GLOBAL_WEBMERCATOR
    num_levels: 22

globals:
  cache:
    base_dir: /app
    lock_dir: /app
    tile_lock_dir: /app

    # Don't use meta buffers for GeoTIFF-based maps!
    # This will lead to strange image artifacts!
    # https://lists.osgeo.org/pipermail/mapproxy/2012-April/001051.html
    meta_size: [1, 1]
    meta_buffer: 0
  http:
    ssl_no_cert_checks: True
  image:
    resampling_method: nearest
