version: '3.0'
services:
  mapserver:
    container_name: mapserver
    build: mapserver
    user: root
    ports:
      - 80:80
    volumes:
      # Format: host path : container path
      - ./mapserver:/srv/mapserver
      - ./output:/srv/historical-maps

  mapproxy:
    container_name: mapproxy
    build: mapproxy
    user: root
    depends_on:
      - mapserver
    volumes:
      # Format: host path : container path
      - ./mapproxy:/app
      - ./output/tiles:/mnt/tiles
