version: '3.0'
services:
  mapserver:
    container_name: mapserver
    build: mapserver
    user: root
    ports:
      - "80:80"
    volumes:
      - /mnt/publieke-werken/:/srv/mapserver/publieke-werken/

  kaart:
    container_name: mapproxy
    build: mapproxy
    user: root
    depends_on:
      - mapserver
    command: >
      mapproxy-seed -c 6 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=kaart_rd
    volumes:
      - "/mnt/tiles:/mnt/tiles"
