services:
  demo:
  wmts:
    md:
      # metadata used in capabilities documents
      title: City Data Amsterdam
      abstract: Map tile service Gemeente Amsterdam
      online_resource: https://data.amsterdam.nl/
      contact:
        person: n/a
        position: n/a
        organization: Gemeente Amsterdam
        address: n/a
        city: Amsterdam
        postcode: n/a
        country: Netherlands
        phone: n/a
        fax: n/a
        email: datapunt@amsterdam.nl
        fees: 'None'
    restful: false
    kvp: true

layers:
  - name: kaart_rd
    title: Historische Kaarten RD
    sources: [kaart_rd_tiles]

caches:
  kaart_rd_cache:
    grids: [nl_grid]
    sources: [kaart_wms]
    cache_dir: /mnt/tiles
    format: image/png
    cache:
      type: file
      directory_layout: tms

sources:
# Example to tile to locally with the mapserver docker also running:
  kaart_wms:
    type: wms
    req:
      url: http://localhost:80/maps/publieke-werken
      layers: publieke-werken-1943-28992

grids:
  nl_grid:
    srs: EPSG:28992
    tile_size: [256,256]
    origin: sw
    res: [3440.64,1720.32,860.16,430.08,215.04,107.52,53.76,26.88,13.44,6.72,3.36,1.68,0.84,0.42,0.21,0.105,0.0525]
    #     0       1       2      3      4      5      6     7     8     9    10   11   12   13   14   15    16
    bbox: [-285401.920,22598.080,595401.9199999999,903401.9199999999]

  webmercator:
    base: GLOBAL_WEBMERCATOR
    num_levels: 22

globals:
  cache:
    base_dir: '/app'
    lock_dir: '/app'
    tile_lock_dir: '/app'
    meta_size: [4, 4]
    meta_buffer: 128
  http:
    ssl_no_cert_checks: True

  image:
      resampling_method: bicubic
